services:
  frontend:
    container_name: gh-shop-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
      #ports:
    # - 3000:3000
    environment:
      - NEXT_PUBLIC_BASE_URL=https://api.toangtv.live/api
    networks:
      - gh-shop
    depends_on:
      - backend

  backend:
    container_name: gh-shop-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
      #ports:
    # - 8080:8080
    environment:
      - SERVER_URL=https://api.toangtv.live
      - PORT=8080
      - ORIGIN_URL=https://toangtv.live
      - MONGO_URI=mongodb+srv://doadmin:2XL8sulB61k07d49@db-mongodb-sgp1-88647-d9c7186e.mongo.ondigitalocean.com/test?tls=true&authSource=admin&replicaSet=db-mongodb-sgp1-88647
      - TOKEN_SECRET=150131091ad22d4e4acecd1340fef3d6cef0477a3745520756e19c9f2021f37f18bb45aa135049ee36d4ad7439dc8cad72d928c95332c6b8da59c56521d85a56
      - CLOUD_NAME=deynivwng
      - API_KEY=599362517879835
      - API_SECRET=n-V1lOKLqopjMFH2P-JB0jUq9Vk
      - STRIPE_PUBLISHABLE_KEY=pk_test_51QM6EcECJUADH3UmU0SYcHTiFRxpEplzRDfGMxLHoCdFXykdjibypb5KjWFmXN85uLVVA7yO1iMtQwHrws0WiBme00Q8jzOdn5
      - STRIPE_SECRET_KEY=sk_test_51QM6EcECJUADH3UmVYm7SszUqSyZy2fzz3qrdtxt18dWokHvMZkLbMfFGE0KYigTm6wnEb2FBKQRsCQelwXN8met002K6UjxUe
      - SHIPPING_FEE_API=https://api.goship.io/api/ext_v1/rates
      - GOOGLE_CLIENT_ID=332965588325-po6hu1vatm9da0g9p3up52es3g3ofkui.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
    networks:
      - gh-shop
  nginx-proxy-manager:
    container_name: gh-shop-nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 81:81
    volumes:
      # - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
      - backend
    networks:
      - gh-shop

networks:
  gh-shop:
    driver: bridge